export const ANNOTATION_STATUS_PENDENT = 'PENDENT';
export const ANNOTATION_STATUS_PAYED = 'PAYED';
export const ANNOTATION_STATUS_RECIVE = 'RECIVE';
export const ANNOTATION_STATUS_EXPIRED = 'EXPIRED';

export const WARNING_DAYS = 3;

export const ANNOTATION_STATUS_LIST = [
    ANNOTATION_STATUS_PENDENT, ANNOTATION_STATUS_PAYED,ANNOTATION_STATUS_RECIVE,ANNOTATION_STATUS_EXPIRED
];