export const ANNOTATION_STATUS_PENDENT = 'PENDENT';
export const ANNOTATION_STATUS_PAYED = 'PAYED';
export const ANNOTATION_STATUS_RECIVE = 'RECIVE';
export const ANNOTATION_STATUS_EXPIRED = 'EXPIRED';
export const ANNOTATIONS_STATUS = {
    ANNOTATION_STATUS_PENDENT, ANNOTATION_STATUS_PAYED,
    ANNOTATION_STATUS_RECIVE, ANNOTATION_STATUS_EXPIRED
}

export const BILL_TYPE = 'BILL';
export const INCOMING_TYPE = 'PAYMENT';
export const EXPANSE_TYPE = 'EXPANSE';

export const ANNOTATION_TYPES = {BILL_TYPE, INCOMING_TYPE, EXPANSE_TYPE};

const BILL_COLOR = 'red';
const INCOMING_COLOR = 'blue';

export const ANNOTATION_COLORS = {
    BILL_COLOR,INCOMING_COLOR
}

export const BTN_TABLE = {
    [ANNOTATION_TYPES.BILL_TYPE]: 'Pay Bill',
    [ANNOTATION_TYPES.INCOMING_TYPE]: 'Receive Payment',
  };