import { Annotation } from "../lib/types";
import * as ANN_CONSTANTS from "../lib/constants/annotations";

function generateUniqueId() {
  const timestamp = Date.now(); // Current timestamp in milliseconds
  const randomNum = Math.floor(Math.random() * 100000); // Random number between 0 and 99999
  return parseInt(`${timestamp}${randomNum}`);
}

const fakeData: Annotation[] = [
  {
    name: 'Energy Bill',
    id:generateUniqueId(),
    description: '',
    annon_type: ANN_CONSTANTS.BILL_TYPE,
    value: 100.00,
    date: '2023-06-01',
    repeat: 'never',
    status: ANN_CONSTANTS.EXPIRED_STATUS,
  },
  {
    name: 'Daily Payment',
    id:generateUniqueId(),
    description: '',
    annon_type: ANN_CONSTANTS.PAYMENT_TYPE,
    value: 90.00,
    date: '2023-06-01',
    repeat: 'never',
    status: ANN_CONSTANTS.PENDENT_STATUS,
  },
  {
    name: 'Water Bill',
    id:generateUniqueId(),
    description: '',
    annon_type: ANN_CONSTANTS.BILL_TYPE,
    value: 110.00,
    date: '2023-06-12',
    repeat: 'never',
    status: ANN_CONSTANTS.PENDENT_STATUS,
  },
  {
    name: 'Energy Bill',
    id:generateUniqueId(),
    description: '',
    annon_type: ANN_CONSTANTS.BILL_TYPE,
    value: 70,
    date: '2023-06-25',
    repeat: 'never',
    status: ANN_CONSTANTS.PAYED_STATUS,
  },
  {
    name: 'Energy Bill',
    id:generateUniqueId(),
    description: '',
    annon_type: ANN_CONSTANTS.BILL_TYPE,
    value: 100.00,
    date: '2023-06-01',
    repeat: 'never',
    status: ANN_CONSTANTS.EXPIRED_STATUS,
  },
  {
    name: 'Daily Payment',
    id:generateUniqueId(),
    description: '',
    annon_type: ANN_CONSTANTS.PAYMENT_TYPE,
    value: 90.00,
    date: '2023-06-01',
    repeat: 'never',
    status: ANN_CONSTANTS.PENDENT_STATUS,
  },
  {
    name: 'Water Bill',
    id:generateUniqueId(),
    description: '',
    annon_type: ANN_CONSTANTS.BILL_TYPE,
    value: 110.00,
    date: '2023-06-12',
    repeat: 'never',
    status: ANN_CONSTANTS.PENDENT_STATUS,
  },
  {
    name: 'Energy Bill',
    id:generateUniqueId(),
    description: '',
    annon_type: ANN_CONSTANTS.BILL_TYPE,
    value: 70,
    date: '2023-06-25',
    repeat: 'never',
    status: ANN_CONSTANTS.PAYED_STATUS,
  },
  {
    name: 'Gas Bill',
    id:generateUniqueId(),
    description: '',
    annon_type: ANN_CONSTANTS.BILL_TYPE,
    value: 80,
    date: '2023-07-01',
    repeat: 'never',
    status: ANN_CONSTANTS.PENDENT_STATUS,
  },
  {
    name: 'Internet Payment',
    id:generateUniqueId(),
    description: '',
    annon_type: ANN_CONSTANTS.PAYMENT_TYPE,
    value: 50,
    date: '2023-07-05',
    repeat: 'never',
    status: ANN_CONSTANTS.PENDENT_STATUS,
  },
  {
    name: 'Electricity Bill',
    id:generateUniqueId(),
    description: '',
    annon_type: ANN_CONSTANTS.BILL_TYPE,
    value: 120,
    date: '2023-07-12',
    repeat: 'never',
    status: ANN_CONSTANTS.PENDENT_STATUS,
  },
  {
    name: 'Energy Bill',
    id:generateUniqueId(),
    description: '',
    annon_type: ANN_CONSTANTS.BILL_TYPE,
    value: 100.00,
    date: '2023-06-01',
    repeat: 'never',
    status: ANN_CONSTANTS.EXPIRED_STATUS,
  },
  {
    name: 'Daily Payment',
    id:generateUniqueId(),
    description: '',
    annon_type: ANN_CONSTANTS.PAYMENT_TYPE,
    value: 90.00,
    date: '2023-06-01',
    repeat: 'never',
    status: ANN_CONSTANTS.PENDENT_STATUS,
  },
  {
    name: 'Water Bill',
    id:generateUniqueId(),
    description: '',
    annon_type: ANN_CONSTANTS.BILL_TYPE,
    value: 110.00,
    date: '2023-06-12',
    repeat: 'never',
    status: ANN_CONSTANTS.PENDENT_STATUS,
  },
  {
    name: 'Energy Bill',
    id:generateUniqueId(),
    description: '',
    annon_type: ANN_CONSTANTS.BILL_TYPE,
    value: 70,
    date: '2023-06-25',
    repeat: 'never',
    status: ANN_CONSTANTS.PAYED_STATUS,
  },
  {
    name: 'Energy Bill',
    id:generateUniqueId(),
    description: '',
    annon_type: ANN_CONSTANTS.BILL_TYPE,
    value: 100.00,
    date: '2023-06-01',
    repeat: 'never',
    status: ANN_CONSTANTS.EXPIRED_STATUS,
  },
  {
    name: 'Daily Payment',
    id:generateUniqueId(),
    description: '',
    annon_type: ANN_CONSTANTS.PAYMENT_TYPE,
    value: 90.00,
    date: '2023-06-01',
    repeat: 'never',
    status: ANN_CONSTANTS.PENDENT_STATUS,
  },
  {
    name: 'Water Bill',
    id:generateUniqueId(),
    description: '',
    annon_type: ANN_CONSTANTS.BILL_TYPE,
    value: 110.00,
    date: '2023-06-12',
    repeat: 'never',
    status: ANN_CONSTANTS.PENDENT_STATUS,
  },
  {
    name: 'Energy Bill',
    id:generateUniqueId(),
    description: '',
    annon_type: ANN_CONSTANTS.BILL_TYPE,
    value: 70,
    date: '2023-06-25',
    repeat: 'never',
    status: ANN_CONSTANTS.PAYED_STATUS,
  },
  {
    name: 'Gas Bill',
    id:generateUniqueId(),
    description: '',
    annon_type: ANN_CONSTANTS.BILL_TYPE,
    value: 80,
    date: '2023-07-01',
    repeat: 'never',
    status: ANN_CONSTANTS.PENDENT_STATUS,
  },
  {
    name: 'Internet Payment',
    id:generateUniqueId(),
    description: '',
    annon_type: ANN_CONSTANTS.PAYMENT_TYPE,
    value: 50,
    date: '2023-07-05',
    repeat: 'never',
    status: ANN_CONSTANTS.PENDENT_STATUS,
  },
  {
    name: 'Electricity Bill',
    id:generateUniqueId(),
    description: '',
    annon_type: ANN_CONSTANTS.BILL_TYPE,
    value: 120,
    date: '2023-07-12',
    repeat: 'never',
    status: ANN_CONSTANTS.PENDENT_STATUS,
  },
]

export default fakeData;