import { Annotation } from "../lib/types";
import * as ANN_CONSTANTS from "../lib/constants/annotations";[

]
const fakeData: Annotation[] = [
  {
    name: 'Energy Bill',
    id: 1,
    description: '',
    annon_type: ANN_CONSTANTS.BILL_TYPE,
    value: 100.00,
    date: '2023-06-01',
    repeat: 'never',
    status: ANN_CONSTANTS.EXPIRED_STATUS,
  },
  {
    name: 'Daily Payment',
    id: 2,
    description: '',
    annon_type: ANN_CONSTANTS.PAYMENT_TYPE,
    value: 90.00,
    date: '2023-06-01',
    repeat: 'never',
    status: ANN_CONSTANTS.PENDENT_STATUS,
  },
  {
    name: 'Water Bill',
    id: 3,
    description: '',
    annon_type: ANN_CONSTANTS.BILL_TYPE,
    value: 110.00,
    date: '2023-06-12',
    repeat: 'never',
    status: ANN_CONSTANTS.PENDENT_STATUS,
  },
  {
    name: 'Energy Bill',
    id: 4,
    description: '',
    annon_type: ANN_CONSTANTS.BILL_TYPE,
    value: 70,
    date: '2023-06-25',
    repeat: 'never',
    status: ANN_CONSTANTS.PAYED_STATUS,
  },
  {
    name: 'Energy Bill',
    id: 21,
    description: '',
    annon_type: ANN_CONSTANTS.BILL_TYPE,
    value: 100.00,
    date: '2023-06-01',
    repeat: 'never',
    status: ANN_CONSTANTS.EXPIRED_STATUS,
  },
  {
    name: 'Daily Payment',
    id: 2231,
    description: '',
    annon_type: ANN_CONSTANTS.PAYMENT_TYPE,
    value: 90.00,
    date: '2023-06-01',
    repeat: 'never',
    status: ANN_CONSTANTS.PENDENT_STATUS,
  },
  {
    name: 'Water Bill',
    id: 3123,
    description: '',
    annon_type: ANN_CONSTANTS.BILL_TYPE,
    value: 110.00,
    date: '2023-06-12',
    repeat: 'never',
    status: ANN_CONSTANTS.PENDENT_STATUS,
  },
  {
    name: 'Energy Bill',
    id: 412,
    description: '',
    annon_type: ANN_CONSTANTS.BILL_TYPE,
    value: 70,
    date: '2023-06-25',
    repeat: 'never',
    status: ANN_CONSTANTS.PAYED_STATUS,
  },
  {
    name: 'Gas Bill',
    id: 512,
    description: '',
    annon_type: ANN_CONSTANTS.BILL_TYPE,
    value: 80,
    date: '2023-07-01',
    repeat: 'never',
    status: ANN_CONSTANTS.PENDENT_STATUS,
  },
  {
    name: 'Internet Payment',
    id: 6123,
    description: '',
    annon_type: ANN_CONSTANTS.PAYMENT_TYPE,
    value: 50,
    date: '2023-07-05',
    repeat: 'never',
    status: ANN_CONSTANTS.PENDENT_STATUS,
  },
  {
    name: 'Electricity Bill',
    id: 7123,
    description: '',
    annon_type: ANN_CONSTANTS.BILL_TYPE,
    value: 120,
    date: '2023-07-12',
    repeat: 'never',
    status: ANN_CONSTANTS.PENDENT_STATUS,
  },
  {
    name: 'Energy Bill',
    id: 1,
    description: '',
    annon_type: ANN_CONSTANTS.BILL_TYPE,
    value: 100.00,
    date: '2023-06-01',
    repeat: 'never',
    status: ANN_CONSTANTS.EXPIRED_STATUS,
  },
  {
    name: 'Daily Payment',
    id: 2,
    description: '',
    annon_type: ANN_CONSTANTS.PAYMENT_TYPE,
    value: 90.00,
    date: '2023-06-01',
    repeat: 'never',
    status: ANN_CONSTANTS.PENDENT_STATUS,
  },
  {
    name: 'Water Bill',
    id: 3,
    description: '',
    annon_type: ANN_CONSTANTS.BILL_TYPE,
    value: 110.00,
    date: '2023-06-12',
    repeat: 'never',
    status: ANN_CONSTANTS.PENDENT_STATUS,
  },
  {
    name: 'Energy Bill',
    id: 4,
    description: '',
    annon_type: ANN_CONSTANTS.BILL_TYPE,
    value: 70,
    date: '2023-06-25',
    repeat: 'never',
    status: ANN_CONSTANTS.PAYED_STATUS,
  },
  {
    name: 'Energy Bill',
    id: 21,
    description: '',
    annon_type: ANN_CONSTANTS.BILL_TYPE,
    value: 100.00,
    date: '2023-06-01',
    repeat: 'never',
    status: ANN_CONSTANTS.EXPIRED_STATUS,
  },
  {
    name: 'Daily Payment',
    id: 2231,
    description: '',
    annon_type: ANN_CONSTANTS.PAYMENT_TYPE,
    value: 90.00,
    date: '2023-06-01',
    repeat: 'never',
    status: ANN_CONSTANTS.PENDENT_STATUS,
  },
  {
    name: 'Water Bill',
    id: 3123,
    description: '',
    annon_type: ANN_CONSTANTS.BILL_TYPE,
    value: 110.00,
    date: '2023-06-12',
    repeat: 'never',
    status: ANN_CONSTANTS.PENDENT_STATUS,
  },
  {
    name: 'Energy Bill',
    id: 412,
    description: '',
    annon_type: ANN_CONSTANTS.BILL_TYPE,
    value: 70,
    date: '2023-06-25',
    repeat: 'never',
    status: ANN_CONSTANTS.PAYED_STATUS,
  },
  {
    name: 'Gas Bill',
    id: 512,
    description: '',
    annon_type: ANN_CONSTANTS.BILL_TYPE,
    value: 80,
    date: '2023-07-01',
    repeat: 'never',
    status: ANN_CONSTANTS.PENDENT_STATUS,
  },
  {
    name: 'Internet Payment',
    id: 6123,
    description: '',
    annon_type: ANN_CONSTANTS.PAYMENT_TYPE,
    value: 50,
    date: '2023-07-05',
    repeat: 'never',
    status: ANN_CONSTANTS.PENDENT_STATUS,
  },
  {
    name: 'Electricity Bill',
    id: 7123,
    description: '',
    annon_type: ANN_CONSTANTS.BILL_TYPE,
    value: 120,
    date: '2023-07-12',
    repeat: 'never',
    status: ANN_CONSTANTS.PENDENT_STATUS,
  },
]

export default fakeData;